name: Deploy SwiftMeal to VPS Biznet

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploying SwiftMeal to Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🔑 Executing Remote SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: '103.127.135.200'
        username: 'ubuntu'
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/html
          sudo git pull origin main
