name: Deploy SwiftMeal to VPS Biznet

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploying SwiftMeal to Production
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🔑 Executing Remote SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: '103.127.135.200'
        username: 'ubuntu'
        key: ${{ secrets.VPS_SSH_KEY }}
        # Kita tambahkan perintah untuk memastikan git aman dan mereset jika ada konflik
        script: |
          cd /var/www/html
          git fetch --all
          git reset --hard origin/main
